interface Task {
	id: number;
	description: string;
	details?: string;
	created_at: string;
	order: number;
}

// Fake tasks generated by ChatGPT.
export const tasks: Task[] = [
	{
		id: 1,
		description: 'Implement user authentication',
		details: 'Use JWT for token-based authentication',
		created_at: '2024-04-21T08:00:00',
		order: 0,
	},
	{
		id: 2,
		description: 'Create database schema',
		details: 'Design tables for users, posts, and comments',
		created_at: '2024-04-21T09:30:00',
		order: 1,
	},
	{
		id: 3,
		description: 'Setup project repository',
		details: 'Initialize Git repository and add initial files',
		created_at: '2024-04-20T15:45:00',
		order: 2,
	},
	{
		id: 4,
		description: 'Design REST API endpoints',
		details: 'Define routes for CRUD operations',
		created_at: '2024-04-19T11:20:00',
		order: 3,
	},
	{
		id: 5,
		description: 'Implement front-end UI components',
		details: 'Create reusable React components for user interface',
		created_at: '2024-04-18T14:10:00',
		order: 4,
	},
	{
		id: 6,
		description: 'Optimize database queries',
		details: 'Improve query performance using indexing',
		created_at: '2024-04-17T10:55:00',
		order: 5,
	},
	{
		id: 7,
		description: 'Write unit tests for API',
		details: 'Cover endpoints with Jest and Supertest',
		created_at: '2024-04-16T16:30:00',
		order: 6,
	},
	{
		id: 8,
		description: 'Integrate third-party API',
		details: 'Incorporate weather API for real-time data',
		created_at: '2024-04-15T09:00:00',
		order: 7,
	},
	{
		id: 9,
		description: 'Implement error handling',
		details: 'Define global error middleware',
		created_at: '2024-04-14T12:20:00',
		order: 8,
	},
	{
		id: 10,
		description: 'Deploy application to staging',
		details: 'Setup CI/CD pipeline with Docker and Kubernetes',
		created_at: '2024-04-13T17:45:00',
		order: 9,
	},
];
